# Header
menu:
  Home: /
  Demo: /demo




# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
share: Share
fancybox: true

# links 友链
#links: 
#  - Hexo: http://zespia.tw/hexo/
#  - github: https://github.com/


# Sidebar
widgets:
#- search
- music
- category
- recent_posts
- tag
- tagcloud
- links

# Miscellaneous
google_analytics:
duoshuo_shortname: nanc
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: 
music: 
